### PR TITLE
enhancements

### PR DESCRIPTION
**Pull request by airdrummer**
- debug logging
- search_whole_uri
- don't take 1st match
- walk_uri
- replacements
- skip_ignored

### CODE REVIEW

**Comment by airdrummer** [comment]
thanx, leon, sorry bout the accidental delete

**Comment by leonstafford** [comment]
Many thanks for quick respone, @airdrummer! Will try to check these soon. Please ping me if you don't hear back/see this merged in a week.

**Comment by airdrummer** [comment]
i hope u can squash merge

**Comment by leonstafford** [comment]
@airdrummer, of yeah, no worries re lots of commits - Let me know if still working on this one or when it's ready for a review

**Comment by airdrummer** [comment]
orry, been otherwise occupied...an org hired a designer to update the website i wrangle for them, and they don't even know css:-\

so pls go ahead & merge

**Pull request closed without merging**
